// Generated by gencpp from file clb_msgs/Blue_connect.msg
// DO NOT EDIT!


#ifndef CLB_MSGS_MESSAGE_BLUE_CONNECT_H
#define CLB_MSGS_MESSAGE_BLUE_CONNECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clb_msgs
{
template <class ContainerAllocator>
struct Blue_connect_
{
  typedef Blue_connect_<ContainerAllocator> Type;

  Blue_connect_()
    : connect_stats(0)  {
    }
  Blue_connect_(const ContainerAllocator& _alloc)
    : connect_stats(0)  {
  (void)_alloc;
    }



   typedef int32_t _connect_stats_type;
  _connect_stats_type connect_stats;





  typedef boost::shared_ptr< ::clb_msgs::Blue_connect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clb_msgs::Blue_connect_<ContainerAllocator> const> ConstPtr;

}; // struct Blue_connect_

typedef ::clb_msgs::Blue_connect_<std::allocator<void> > Blue_connect;

typedef boost::shared_ptr< ::clb_msgs::Blue_connect > Blue_connectPtr;
typedef boost::shared_ptr< ::clb_msgs::Blue_connect const> Blue_connectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clb_msgs::Blue_connect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clb_msgs::Blue_connect_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clb_msgs::Blue_connect_<ContainerAllocator1> & lhs, const ::clb_msgs::Blue_connect_<ContainerAllocator2> & rhs)
{
  return lhs.connect_stats == rhs.connect_stats;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clb_msgs::Blue_connect_<ContainerAllocator1> & lhs, const ::clb_msgs::Blue_connect_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::Blue_connect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::Blue_connect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::Blue_connect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::Blue_connect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::Blue_connect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::Blue_connect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clb_msgs::Blue_connect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "689b4c4cbf04148501838010cd8ac299";
  }

  static const char* value(const ::clb_msgs::Blue_connect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x689b4c4cbf041485ULL;
  static const uint64_t static_value2 = 0x01838010cd8ac299ULL;
};

template<class ContainerAllocator>
struct DataType< ::clb_msgs::Blue_connect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clb_msgs/Blue_connect";
  }

  static const char* value(const ::clb_msgs::Blue_connect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clb_msgs::Blue_connect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 connect_stats\n"
;
  }

  static const char* value(const ::clb_msgs::Blue_connect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clb_msgs::Blue_connect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.connect_stats);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Blue_connect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clb_msgs::Blue_connect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clb_msgs::Blue_connect_<ContainerAllocator>& v)
  {
    s << indent << "connect_stats: ";
    Printer<int32_t>::stream(s, indent + "  ", v.connect_stats);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLB_MSGS_MESSAGE_BLUE_CONNECT_H
