// Generated by gencpp from file clb_msgs/Buzzer.msg
// DO NOT EDIT!


#ifndef CLB_MSGS_MESSAGE_BUZZER_H
#define CLB_MSGS_MESSAGE_BUZZER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clb_msgs
{
template <class ContainerAllocator>
struct Buzzer_
{
  typedef Buzzer_<ContainerAllocator> Type;

  Buzzer_()
    : BUZZER1(0)  {
    }
  Buzzer_(const ContainerAllocator& _alloc)
    : BUZZER1(0)  {
  (void)_alloc;
    }



   typedef int32_t _BUZZER1_type;
  _BUZZER1_type BUZZER1;





  typedef boost::shared_ptr< ::clb_msgs::Buzzer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clb_msgs::Buzzer_<ContainerAllocator> const> ConstPtr;

}; // struct Buzzer_

typedef ::clb_msgs::Buzzer_<std::allocator<void> > Buzzer;

typedef boost::shared_ptr< ::clb_msgs::Buzzer > BuzzerPtr;
typedef boost::shared_ptr< ::clb_msgs::Buzzer const> BuzzerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clb_msgs::Buzzer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clb_msgs::Buzzer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clb_msgs::Buzzer_<ContainerAllocator1> & lhs, const ::clb_msgs::Buzzer_<ContainerAllocator2> & rhs)
{
  return lhs.BUZZER1 == rhs.BUZZER1;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clb_msgs::Buzzer_<ContainerAllocator1> & lhs, const ::clb_msgs::Buzzer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::Buzzer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::Buzzer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::Buzzer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::Buzzer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::Buzzer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::Buzzer_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clb_msgs::Buzzer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "961d0bf227fa8152deae5f5d68ec086e";
  }

  static const char* value(const ::clb_msgs::Buzzer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x961d0bf227fa8152ULL;
  static const uint64_t static_value2 = 0xdeae5f5d68ec086eULL;
};

template<class ContainerAllocator>
struct DataType< ::clb_msgs::Buzzer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clb_msgs/Buzzer";
  }

  static const char* value(const ::clb_msgs::Buzzer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clb_msgs::Buzzer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 BUZZER1\n"
;
  }

  static const char* value(const ::clb_msgs::Buzzer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clb_msgs::Buzzer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.BUZZER1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Buzzer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clb_msgs::Buzzer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clb_msgs::Buzzer_<ContainerAllocator>& v)
  {
    s << indent << "BUZZER1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.BUZZER1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLB_MSGS_MESSAGE_BUZZER_H
