// Generated by gencpp from file clb_msgs/GripperRequest.msg
// DO NOT EDIT!


#ifndef CLB_MSGS_MESSAGE_GRIPPERREQUEST_H
#define CLB_MSGS_MESSAGE_GRIPPERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clb_msgs
{
template <class ContainerAllocator>
struct GripperRequest_
{
  typedef GripperRequest_<ContainerAllocator> Type;

  GripperRequest_()
    : step(0)
    , time(0)  {
    }
  GripperRequest_(const ContainerAllocator& _alloc)
    : step(0)
    , time(0)  {
  (void)_alloc;
    }



   typedef int16_t _step_type;
  _step_type step;

   typedef int16_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::clb_msgs::GripperRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clb_msgs::GripperRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GripperRequest_

typedef ::clb_msgs::GripperRequest_<std::allocator<void> > GripperRequest;

typedef boost::shared_ptr< ::clb_msgs::GripperRequest > GripperRequestPtr;
typedef boost::shared_ptr< ::clb_msgs::GripperRequest const> GripperRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clb_msgs::GripperRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clb_msgs::GripperRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clb_msgs::GripperRequest_<ContainerAllocator1> & lhs, const ::clb_msgs::GripperRequest_<ContainerAllocator2> & rhs)
{
  return lhs.step == rhs.step &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clb_msgs::GripperRequest_<ContainerAllocator1> & lhs, const ::clb_msgs::GripperRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::GripperRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::GripperRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::GripperRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::GripperRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::GripperRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::GripperRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clb_msgs::GripperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e27b20d61c16bcd76ef982854742171b";
  }

  static const char* value(const ::clb_msgs::GripperRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe27b20d61c16bcd7ULL;
  static const uint64_t static_value2 = 0x6ef982854742171bULL;
};

template<class ContainerAllocator>
struct DataType< ::clb_msgs::GripperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clb_msgs/GripperRequest";
  }

  static const char* value(const ::clb_msgs::GripperRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clb_msgs::GripperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 step\n"
"int16 time\n"
"\n"
;
  }

  static const char* value(const ::clb_msgs::GripperRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clb_msgs::GripperRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.step);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clb_msgs::GripperRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clb_msgs::GripperRequest_<ContainerAllocator>& v)
  {
    s << indent << "step: ";
    Printer<int16_t>::stream(s, indent + "  ", v.step);
    s << indent << "time: ";
    Printer<int16_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLB_MSGS_MESSAGE_GRIPPERREQUEST_H
