// Generated by gencpp from file clb_msgs/Gripper.msg
// DO NOT EDIT!


#ifndef CLB_MSGS_MESSAGE_GRIPPER_H
#define CLB_MSGS_MESSAGE_GRIPPER_H

#include <ros/service_traits.h>


#include <clb_msgs/GripperRequest.h>
#include <clb_msgs/GripperResponse.h>


namespace clb_msgs
{

struct Gripper
{

typedef GripperRequest Request;
typedef GripperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Gripper
} // namespace clb_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clb_msgs::Gripper > {
  static const char* value()
  {
    return "e27b20d61c16bcd76ef982854742171b";
  }

  static const char* value(const ::clb_msgs::Gripper&) { return value(); }
};

template<>
struct DataType< ::clb_msgs::Gripper > {
  static const char* value()
  {
    return "clb_msgs/Gripper";
  }

  static const char* value(const ::clb_msgs::Gripper&) { return value(); }
};


// service_traits::MD5Sum< ::clb_msgs::GripperRequest> should match
// service_traits::MD5Sum< ::clb_msgs::Gripper >
template<>
struct MD5Sum< ::clb_msgs::GripperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clb_msgs::Gripper >::value();
  }
  static const char* value(const ::clb_msgs::GripperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clb_msgs::GripperRequest> should match
// service_traits::DataType< ::clb_msgs::Gripper >
template<>
struct DataType< ::clb_msgs::GripperRequest>
{
  static const char* value()
  {
    return DataType< ::clb_msgs::Gripper >::value();
  }
  static const char* value(const ::clb_msgs::GripperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clb_msgs::GripperResponse> should match
// service_traits::MD5Sum< ::clb_msgs::Gripper >
template<>
struct MD5Sum< ::clb_msgs::GripperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clb_msgs::Gripper >::value();
  }
  static const char* value(const ::clb_msgs::GripperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clb_msgs::GripperResponse> should match
// service_traits::DataType< ::clb_msgs::Gripper >
template<>
struct DataType< ::clb_msgs::GripperResponse>
{
  static const char* value()
  {
    return DataType< ::clb_msgs::Gripper >::value();
  }
  static const char* value(const ::clb_msgs::GripperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLB_MSGS_MESSAGE_GRIPPER_H
