// Generated by gencpp from file clb_msgs/PoseRequest.msg
// DO NOT EDIT!


#ifndef CLB_MSGS_MESSAGE_POSEREQUEST_H
#define CLB_MSGS_MESSAGE_POSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clb_msgs
{
template <class ContainerAllocator>
struct PoseRequest_
{
  typedef PoseRequest_<ContainerAllocator> Type;

  PoseRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , rtoary(0.0)
    , time(0)  {
    }
  PoseRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , rtoary(0.0)
    , time(0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _rtoary_type;
  _rtoary_type rtoary;

   typedef int16_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::clb_msgs::PoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clb_msgs::PoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PoseRequest_

typedef ::clb_msgs::PoseRequest_<std::allocator<void> > PoseRequest;

typedef boost::shared_ptr< ::clb_msgs::PoseRequest > PoseRequestPtr;
typedef boost::shared_ptr< ::clb_msgs::PoseRequest const> PoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clb_msgs::PoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clb_msgs::PoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clb_msgs::PoseRequest_<ContainerAllocator1> & lhs, const ::clb_msgs::PoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.rtoary == rhs.rtoary &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clb_msgs::PoseRequest_<ContainerAllocator1> & lhs, const ::clb_msgs::PoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::PoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::PoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::PoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::PoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::PoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::PoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clb_msgs::PoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4258fd17a5d5267d5a22ad00faa1382";
  }

  static const char* value(const ::clb_msgs::PoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4258fd17a5d5267ULL;
  static const uint64_t static_value2 = 0xd5a22ad00faa1382ULL;
};

template<class ContainerAllocator>
struct DataType< ::clb_msgs::PoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clb_msgs/PoseRequest";
  }

  static const char* value(const ::clb_msgs::PoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clb_msgs::PoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 rtoary\n"
"int16 time\n"
"\n"
;
  }

  static const char* value(const ::clb_msgs::PoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clb_msgs::PoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.rtoary);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clb_msgs::PoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clb_msgs::PoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "rtoary: ";
    Printer<float>::stream(s, indent + "  ", v.rtoary);
    s << indent << "time: ";
    Printer<int16_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLB_MSGS_MESSAGE_POSEREQUEST_H
