// Generated by gencpp from file clb_msgs/Pose.msg
// DO NOT EDIT!


#ifndef CLB_MSGS_MESSAGE_POSE_H
#define CLB_MSGS_MESSAGE_POSE_H

#include <ros/service_traits.h>


#include <clb_msgs/PoseRequest.h>
#include <clb_msgs/PoseResponse.h>


namespace clb_msgs
{

struct Pose
{

typedef PoseRequest Request;
typedef PoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Pose
} // namespace clb_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clb_msgs::Pose > {
  static const char* value()
  {
    return "c4258fd17a5d5267d5a22ad00faa1382";
  }

  static const char* value(const ::clb_msgs::Pose&) { return value(); }
};

template<>
struct DataType< ::clb_msgs::Pose > {
  static const char* value()
  {
    return "clb_msgs/Pose";
  }

  static const char* value(const ::clb_msgs::Pose&) { return value(); }
};


// service_traits::MD5Sum< ::clb_msgs::PoseRequest> should match
// service_traits::MD5Sum< ::clb_msgs::Pose >
template<>
struct MD5Sum< ::clb_msgs::PoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clb_msgs::Pose >::value();
  }
  static const char* value(const ::clb_msgs::PoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clb_msgs::PoseRequest> should match
// service_traits::DataType< ::clb_msgs::Pose >
template<>
struct DataType< ::clb_msgs::PoseRequest>
{
  static const char* value()
  {
    return DataType< ::clb_msgs::Pose >::value();
  }
  static const char* value(const ::clb_msgs::PoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clb_msgs::PoseResponse> should match
// service_traits::MD5Sum< ::clb_msgs::Pose >
template<>
struct MD5Sum< ::clb_msgs::PoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clb_msgs::Pose >::value();
  }
  static const char* value(const ::clb_msgs::PoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clb_msgs::PoseResponse> should match
// service_traits::DataType< ::clb_msgs::Pose >
template<>
struct DataType< ::clb_msgs::PoseResponse>
{
  static const char* value()
  {
    return DataType< ::clb_msgs::Pose >::value();
  }
  static const char* value(const ::clb_msgs::PoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLB_MSGS_MESSAGE_POSE_H
