// Generated by gencpp from file clb_msgs/ps2_value.msg
// DO NOT EDIT!


#ifndef CLB_MSGS_MESSAGE_PS2_VALUE_H
#define CLB_MSGS_MESSAGE_PS2_VALUE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clb_msgs
{
template <class ContainerAllocator>
struct ps2_value_
{
  typedef ps2_value_<ContainerAllocator> Type;

  ps2_value_()
    : data()  {
      data.assign(0);
  }
  ps2_value_(const ContainerAllocator& _alloc)
    : data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef boost::array<uint8_t, 10>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::clb_msgs::ps2_value_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clb_msgs::ps2_value_<ContainerAllocator> const> ConstPtr;

}; // struct ps2_value_

typedef ::clb_msgs::ps2_value_<std::allocator<void> > ps2_value;

typedef boost::shared_ptr< ::clb_msgs::ps2_value > ps2_valuePtr;
typedef boost::shared_ptr< ::clb_msgs::ps2_value const> ps2_valueConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clb_msgs::ps2_value_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clb_msgs::ps2_value_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clb_msgs::ps2_value_<ContainerAllocator1> & lhs, const ::clb_msgs::ps2_value_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clb_msgs::ps2_value_<ContainerAllocator1> & lhs, const ::clb_msgs::ps2_value_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::ps2_value_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::ps2_value_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::ps2_value_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::ps2_value_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::ps2_value_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::ps2_value_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clb_msgs::ps2_value_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c05a05733f13fb160c661ca1798fdba";
  }

  static const char* value(const ::clb_msgs::ps2_value_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c05a05733f13fb1ULL;
  static const uint64_t static_value2 = 0x60c661ca1798fdbaULL;
};

template<class ContainerAllocator>
struct DataType< ::clb_msgs::ps2_value_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clb_msgs/ps2_value";
  }

  static const char* value(const ::clb_msgs::ps2_value_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clb_msgs::ps2_value_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[10] data\n"
;
  }

  static const char* value(const ::clb_msgs::ps2_value_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clb_msgs::ps2_value_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ps2_value_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clb_msgs::ps2_value_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clb_msgs::ps2_value_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLB_MSGS_MESSAGE_PS2_VALUE_H
