// Generated by gencpp from file clb_msgs/RobotVoiceCtrl.msg
// DO NOT EDIT!


#ifndef CLB_MSGS_MESSAGE_ROBOTVOICECTRL_H
#define CLB_MSGS_MESSAGE_ROBOTVOICECTRL_H

#include <ros/service_traits.h>


#include <clb_msgs/RobotVoiceCtrlRequest.h>
#include <clb_msgs/RobotVoiceCtrlResponse.h>


namespace clb_msgs
{

struct RobotVoiceCtrl
{

typedef RobotVoiceCtrlRequest Request;
typedef RobotVoiceCtrlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotVoiceCtrl
} // namespace clb_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clb_msgs::RobotVoiceCtrl > {
  static const char* value()
  {
    return "99d7cbf41203ea07c76e17ef42eda7f5";
  }

  static const char* value(const ::clb_msgs::RobotVoiceCtrl&) { return value(); }
};

template<>
struct DataType< ::clb_msgs::RobotVoiceCtrl > {
  static const char* value()
  {
    return "clb_msgs/RobotVoiceCtrl";
  }

  static const char* value(const ::clb_msgs::RobotVoiceCtrl&) { return value(); }
};


// service_traits::MD5Sum< ::clb_msgs::RobotVoiceCtrlRequest> should match
// service_traits::MD5Sum< ::clb_msgs::RobotVoiceCtrl >
template<>
struct MD5Sum< ::clb_msgs::RobotVoiceCtrlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clb_msgs::RobotVoiceCtrl >::value();
  }
  static const char* value(const ::clb_msgs::RobotVoiceCtrlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clb_msgs::RobotVoiceCtrlRequest> should match
// service_traits::DataType< ::clb_msgs::RobotVoiceCtrl >
template<>
struct DataType< ::clb_msgs::RobotVoiceCtrlRequest>
{
  static const char* value()
  {
    return DataType< ::clb_msgs::RobotVoiceCtrl >::value();
  }
  static const char* value(const ::clb_msgs::RobotVoiceCtrlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clb_msgs::RobotVoiceCtrlResponse> should match
// service_traits::MD5Sum< ::clb_msgs::RobotVoiceCtrl >
template<>
struct MD5Sum< ::clb_msgs::RobotVoiceCtrlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clb_msgs::RobotVoiceCtrl >::value();
  }
  static const char* value(const ::clb_msgs::RobotVoiceCtrlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clb_msgs::RobotVoiceCtrlResponse> should match
// service_traits::DataType< ::clb_msgs::RobotVoiceCtrl >
template<>
struct DataType< ::clb_msgs::RobotVoiceCtrlResponse>
{
  static const char* value()
  {
    return DataType< ::clb_msgs::RobotVoiceCtrl >::value();
  }
  static const char* value(const ::clb_msgs::RobotVoiceCtrlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLB_MSGS_MESSAGE_ROBOTVOICECTRL_H
