// Generated by gencpp from file clb_msgs/ServoAngle.msg
// DO NOT EDIT!


#ifndef CLB_MSGS_MESSAGE_SERVOANGLE_H
#define CLB_MSGS_MESSAGE_SERVOANGLE_H

#include <ros/service_traits.h>


#include <clb_msgs/ServoAngleRequest.h>
#include <clb_msgs/ServoAngleResponse.h>


namespace clb_msgs
{

struct ServoAngle
{

typedef ServoAngleRequest Request;
typedef ServoAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServoAngle
} // namespace clb_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clb_msgs::ServoAngle > {
  static const char* value()
  {
    return "b1d39e7bb90536edb373b61068d04284";
  }

  static const char* value(const ::clb_msgs::ServoAngle&) { return value(); }
};

template<>
struct DataType< ::clb_msgs::ServoAngle > {
  static const char* value()
  {
    return "clb_msgs/ServoAngle";
  }

  static const char* value(const ::clb_msgs::ServoAngle&) { return value(); }
};


// service_traits::MD5Sum< ::clb_msgs::ServoAngleRequest> should match
// service_traits::MD5Sum< ::clb_msgs::ServoAngle >
template<>
struct MD5Sum< ::clb_msgs::ServoAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clb_msgs::ServoAngle >::value();
  }
  static const char* value(const ::clb_msgs::ServoAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clb_msgs::ServoAngleRequest> should match
// service_traits::DataType< ::clb_msgs::ServoAngle >
template<>
struct DataType< ::clb_msgs::ServoAngleRequest>
{
  static const char* value()
  {
    return DataType< ::clb_msgs::ServoAngle >::value();
  }
  static const char* value(const ::clb_msgs::ServoAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clb_msgs::ServoAngleResponse> should match
// service_traits::MD5Sum< ::clb_msgs::ServoAngle >
template<>
struct MD5Sum< ::clb_msgs::ServoAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clb_msgs::ServoAngle >::value();
  }
  static const char* value(const ::clb_msgs::ServoAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clb_msgs::ServoAngleResponse> should match
// service_traits::DataType< ::clb_msgs::ServoAngle >
template<>
struct DataType< ::clb_msgs::ServoAngleResponse>
{
  static const char* value()
  {
    return DataType< ::clb_msgs::ServoAngle >::value();
  }
  static const char* value(const ::clb_msgs::ServoAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLB_MSGS_MESSAGE_SERVOANGLE_H
