// Generated by gencpp from file clb_msgs/ShootRequest.msg
// DO NOT EDIT!


#ifndef CLB_MSGS_MESSAGE_SHOOTREQUEST_H
#define CLB_MSGS_MESSAGE_SHOOTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clb_msgs
{
template <class ContainerAllocator>
struct ShootRequest_
{
  typedef ShootRequest_<ContainerAllocator> Type;

  ShootRequest_()
    : time(0)  {
    }
  ShootRequest_(const ContainerAllocator& _alloc)
    : time(0)  {
  (void)_alloc;
    }



   typedef int16_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::clb_msgs::ShootRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clb_msgs::ShootRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ShootRequest_

typedef ::clb_msgs::ShootRequest_<std::allocator<void> > ShootRequest;

typedef boost::shared_ptr< ::clb_msgs::ShootRequest > ShootRequestPtr;
typedef boost::shared_ptr< ::clb_msgs::ShootRequest const> ShootRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clb_msgs::ShootRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clb_msgs::ShootRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clb_msgs::ShootRequest_<ContainerAllocator1> & lhs, const ::clb_msgs::ShootRequest_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clb_msgs::ShootRequest_<ContainerAllocator1> & lhs, const ::clb_msgs::ShootRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::ShootRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::ShootRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::ShootRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::ShootRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::ShootRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::ShootRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clb_msgs::ShootRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8e8bf26b20382c114e84bf5da39d6e4";
  }

  static const char* value(const ::clb_msgs::ShootRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8e8bf26b20382c1ULL;
  static const uint64_t static_value2 = 0x14e84bf5da39d6e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::clb_msgs::ShootRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clb_msgs/ShootRequest";
  }

  static const char* value(const ::clb_msgs::ShootRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clb_msgs::ShootRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 time\n"
"\n"
;
  }

  static const char* value(const ::clb_msgs::ShootRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clb_msgs::ShootRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShootRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clb_msgs::ShootRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clb_msgs::ShootRequest_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<int16_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLB_MSGS_MESSAGE_SHOOTREQUEST_H
