// Generated by gencpp from file clb_msgs/ShootResponse.msg
// DO NOT EDIT!


#ifndef CLB_MSGS_MESSAGE_SHOOTRESPONSE_H
#define CLB_MSGS_MESSAGE_SHOOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clb_msgs
{
template <class ContainerAllocator>
struct ShootResponse_
{
  typedef ShootResponse_<ContainerAllocator> Type;

  ShootResponse_()
    {
    }
  ShootResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::clb_msgs::ShootResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clb_msgs::ShootResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ShootResponse_

typedef ::clb_msgs::ShootResponse_<std::allocator<void> > ShootResponse;

typedef boost::shared_ptr< ::clb_msgs::ShootResponse > ShootResponsePtr;
typedef boost::shared_ptr< ::clb_msgs::ShootResponse const> ShootResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clb_msgs::ShootResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clb_msgs::ShootResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace clb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::ShootResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::ShootResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::ShootResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::ShootResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::ShootResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::ShootResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clb_msgs::ShootResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::clb_msgs::ShootResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::clb_msgs::ShootResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clb_msgs/ShootResponse";
  }

  static const char* value(const ::clb_msgs::ShootResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clb_msgs::ShootResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::clb_msgs::ShootResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clb_msgs::ShootResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShootResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clb_msgs::ShootResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::clb_msgs::ShootResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CLB_MSGS_MESSAGE_SHOOTRESPONSE_H
