// Generated by gencpp from file clb_msgs/Ultrasonic.msg
// DO NOT EDIT!


#ifndef CLB_MSGS_MESSAGE_ULTRASONIC_H
#define CLB_MSGS_MESSAGE_ULTRASONIC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clb_msgs
{
template <class ContainerAllocator>
struct Ultrasonic_
{
  typedef Ultrasonic_<ContainerAllocator> Type;

  Ultrasonic_()
    : front(0.0)
    , left(0.0)
    , right(0.0)  {
    }
  Ultrasonic_(const ContainerAllocator& _alloc)
    : front(0.0)
    , left(0.0)
    , right(0.0)  {
  (void)_alloc;
    }



   typedef float _front_type;
  _front_type front;

   typedef float _left_type;
  _left_type left;

   typedef float _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::clb_msgs::Ultrasonic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clb_msgs::Ultrasonic_<ContainerAllocator> const> ConstPtr;

}; // struct Ultrasonic_

typedef ::clb_msgs::Ultrasonic_<std::allocator<void> > Ultrasonic;

typedef boost::shared_ptr< ::clb_msgs::Ultrasonic > UltrasonicPtr;
typedef boost::shared_ptr< ::clb_msgs::Ultrasonic const> UltrasonicConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clb_msgs::Ultrasonic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clb_msgs::Ultrasonic_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clb_msgs::Ultrasonic_<ContainerAllocator1> & lhs, const ::clb_msgs::Ultrasonic_<ContainerAllocator2> & rhs)
{
  return lhs.front == rhs.front &&
    lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clb_msgs::Ultrasonic_<ContainerAllocator1> & lhs, const ::clb_msgs::Ultrasonic_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::Ultrasonic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clb_msgs::Ultrasonic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::Ultrasonic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clb_msgs::Ultrasonic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::Ultrasonic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clb_msgs::Ultrasonic_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clb_msgs::Ultrasonic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c69b6708342d9a4721f01e55dbb0d446";
  }

  static const char* value(const ::clb_msgs::Ultrasonic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc69b6708342d9a47ULL;
  static const uint64_t static_value2 = 0x21f01e55dbb0d446ULL;
};

template<class ContainerAllocator>
struct DataType< ::clb_msgs::Ultrasonic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clb_msgs/Ultrasonic";
  }

  static const char* value(const ::clb_msgs::Ultrasonic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clb_msgs::Ultrasonic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 front\n"
"float32 left\n"
"float32 right \n"
;
  }

  static const char* value(const ::clb_msgs::Ultrasonic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clb_msgs::Ultrasonic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.front);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ultrasonic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clb_msgs::Ultrasonic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clb_msgs::Ultrasonic_<ContainerAllocator>& v)
  {
    s << indent << "front: ";
    Printer<float>::stream(s, indent + "  ", v.front);
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLB_MSGS_MESSAGE_ULTRASONIC_H
